### ISSUE TITLE
为什么与一个python版计算出来的结果不一样？

### ISSUE THREAD

**Issue by deepzliu** [yanyiwu/simhash#16]
您好，python版: https://github.com/leonsim/simhash, 用的就是本代码中的那段文字。

**Comment by DonghuaLau** [comment]
计算速度要慢很多，是因为有词法分析器吗？

**Comment by yanyiwu** [comment]
1. 计算出来的结果不一样是很正常的，你可以看一下simhash的原理就知道了。
2. c++的程序速度比python的快也是符合预期的。

**Comment by DonghuaLau** [comment]
2.是您这个版本比python那个版本慢很多。当然我只是简单的测试了下。

**Comment by yanyiwu** [comment]
你测试是把加载词典也算进去了吧，那当然慢了。

发自我的 iPhone
