### ISSUE TITLE
最简的两段字符串进行比较，怎么弄？

### ISSUE THREAD

**Issue by mejinke** [yanyiwu/simhash#6]
我不是C程序员。 另外我想问一下 这个程序有没有办法让别的语言程序调用？或是做一个简单的web服务?

**Comment by yanyiwu** [comment]
Q： 最简的两段字符串进行比较，怎么弄？
A： 对这两段字符串计算出对应的simhash值，然后对比这两个simhash值。
我猜你对simhash值的用法还不了解？你可以先去了解一下这个算法的原理和用途。详见 [simhash算法原理及实现](http://yanyiwu.com/work/2014/01/30/simhash-shi-xian-xiang-jie.html) 

Q: 做一个简单的web服务?
A: 这个可以有。我搞一个简单的 `simhash_server` 出来试试。

**Comment by yanyiwu** [comment]
[simhash_server](https://github.com/yanyiwu/simhash_server)
