### ISSUE TITLE
gcc4.4.6编译失败，报错error: invalid conversion from ‘long int’ to ‘const CppJieba::DictUnit*’

### ISSUE THREAD

**Issue by yunchenran** [yanyiwu/simhash#7]
[ 16%] Building CXX object src/CMakeFiles/simhash.demo.dir/main.cpp.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/stl_algobase.h:66,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/ios:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/iostream:40,
                 from /search/billczhang/xfs/simhash/src/main.cpp:2:
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/stl_pair.h: In constructor ‘std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = size_t&, _U2 = long int, _T1 = long unsigned int, _T2 = const CppJieba::DictUnit*]’:
/search/billczhang/xfs/simhash/src/CppJieba/MPSegment.hpp:96:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/stl_pair.h:90: error: invalid conversion from ‘long int’ to ‘const CppJieba::DictUnit*’
make[2]: *** [src/CMakeFiles/simhash.demo.dir/main.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/simhash.demo.dir/all] Error 2
make: *** [all] Error 2

**Comment by yanyiwu** [comment]
你更新一下最新代码试试，这个问题应该已经解决了。

**Comment by yunchenran** [comment]
好的 可以了 多谢~
